### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by Jhin3433** [HKUST-KnowComp/ASER#18]
Starting corenlp client at port 9000
2021-09-02 16:46:22 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
2021-09-02 16:46:22 INFO: Writing properties to tmp file: corenlp_server-cb151c508e734d31.props
2021-09-02 16:46:22 INFO: Starting server with command: java -Xmx4G -cp /home/iielct/stanza_corenlp/* edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 99999 -threads 5 -maxCharLength 100000 -quiet False -serverProperties corenlp_server-cb151c508e734d31.props -annotators tokenize,ssplit,pos,lemma,parse,ner -preload -outputFormat serialized
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLPServer
Traceback (most recent call last):
  File "/home/iielct/anaconda3/envs/ASER/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/iielct/anaconda3/envs/ASER/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/iielct/.vscode-server/extensions/ms-python.python-2021.8.1159798656/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/iielct/.vscode-server/extensions/ms-python.python-2021.8.1159798656/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/iielct/.vscode-server/extensions/ms-python.python-2021.8.1159798656/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/iielct/anaconda3/envs/ASER/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/iielct/anaconda3/envs/ASER/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/iielct/anaconda3/envs/ASER/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/iielct/wei/ASER/test.py", line 7, in <module>
    corenlp_path="stanford-corenlp-3.9.2", corenlp_port=9000
  File "/home/iielct/wei/ASER/aser/extract/aser_extractor.py", line 775, in __init__
    super().__init__(corenlp_path, corenlp_port, **kw)
  File "/home/iielct/wei/ASER/aser/extract/aser_extractor.py", line 29, in __init__
    _, self.is_externel_corenlp = get_corenlp_client(corenlp_path=self.corenlp_path, corenlp_port=self.corenlp_port)
  File "/home/iielct/wei/ASER/aser/extract/utils.py", line 115, in get_corenlp_client
    corenlp_client.annotate("hello world", annotators=list(annotators), output_format="json")
  File "/home/iielct/anaconda3/envs/ASER/lib/python3.7/site-packages/stanza/server/client.py", line 523, in annotate
    r = self._request(text.encode('utf-8'), request_properties, reset_default, **kwargs)
  File "/home/iielct/anaconda3/envs/ASER/lib/python3.7/site-packages/stanza/server/client.py", line 436, in _request
    self.ensure_alive()
  File "/home/iielct/anaconda3/envs/ASER/lib/python3.7/site-packages/stanza/server/client.py", line 218, in ensure_alive
    raise PermanentlyFailedException("Timed out waiting for service to come alive.")
stanza.server.client.PermanentlyFailedException: Timed out waiting for service to come alive.
Exception ignored in: <function BaseASERExtractor.__del__ at 0x7f9e36683950>
Traceback (most recent call last):
  File "/home/iielct/wei/ASER/aser/extract/aser_extractor.py", line 47, in __del__
    self.close()
  File "/home/iielct/wei/ASER/aser/extract/aser_extractor.py", line 38, in close
    if not self.is_externel_corenlp:
AttributeError: 'DiscourseASERExtractor' object has no attribute 'is_externel_corenlp'

**Comment by seanliu96** [comment]
Hi, could you please try two possible solutions?

1. manually set JAVA_HOME and CLASSPATH
2. locally run `java -Xmx4G -cp * edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 99999 -threads 5 -maxCharLength 100000 -quiet False -serverProperties corenlp_server-cb151c508e734d31.props -annotators tokenize,ssplit,pos,lemma,parse,ner -preload -outputFormat serialized` in `/home/iielct/stanza_corenlp/` and try again.

**Comment by seanliu96** [comment]
Hi, if your problem has been solved, please close the issue to let others know. Thanks.

**Comment by Jhin3433** [comment]
I use the code` CORENLP_HOME=./stanford-corenlp-3.9.2/  python XXX.py `to run successfully. Thanks!
