### ISSUE TITLE
stanza.server.client.PermanentlyFailedException: Timed out waiting for service to come alive.

### ISSUE THREAD

**Issue by fpalll** [HKUST-KnowComp/ASER#39]
2022-11-15 08:49:22 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
2022-11-15 08:49:22 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
2022-11-15 08:49:22 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
/home/user18/anaconda3/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.22.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
[probase-conceptualize] Loading Probase files...
[probase-conceptualize] Building index...
100%|███████████████████████████| 33377320/33377320 [02:16<00:00, 244115.55it/s]
[probase-conceptualize] Loading data finished in 145.87 s
[2022-11-15 08:51:49,120 INFO] Starting the pipeline.
[2022-11-15 08:51:49,121 INFO] Processing raw data from raw.
[2022-11-15 08:51:49,121 INFO] Number of files: 1.
2022-11-15 08:51:49 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
[2022-11-15 08:51:49,121 WARNING] Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
Traceback (most recent call last):
  File "/home/user18/anaconda3/bin/aser-pipe", line 33, in <module>
    sys.exit(load_entry_point('aser==2.0.0', 'console_scripts', 'aser-pipe')())
  File "/home/user18/anaconda3/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/pipe/cli.py", line 18, in main
    ASERPipe(args).run()
  File "/home/user18/anaconda3/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/pipe/__init__.py", line 207, in run
    eid2sids, rid2sids, eid2eventuality, rid2relation = extract_files(
  File "/home/user18/anaconda3/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/pipe/__init__.py", line 57, in extract_files
    x_eid2sids, x_rid2sids, x_eid2eventuality, x_rid2relation = extract_file(
  File "/home/user18/anaconda3/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/extract/utils.py", line 567, in extract_file
    processed_data = process_raw_file(raw_path, processed_path, sentence_parser)
  File "/home/user18/anaconda3/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/extract/utils.py", line 520, in process_raw_file
    return sentence_parser.parse_raw_file(raw_path, processed_path, max_len=MAX_LEN)
  File "/home/user18/anaconda3/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/extract/sentence_parser.py", line 94, in parse_raw_file
    paragraphs[i] = self.parse(paragraphs[i], annotators=annotators, max_len=max_len)
  File "/home/user18/anaconda3/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/extract/sentence_parser.py", line 126, in parse
    parsed_para = parse_sentense_with_stanford(paragraph, corenlp_client, annotators, max_len)
  File "/home/user18/anaconda3/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/extract/utils.py", line 218, in parse_sentense_with_stanford
    parsed_sentence = corenlp_client.annotate(sentence, annotators=annotators,
  File "/home/user18/anaconda3/lib/python3.9/site-packages/stanza/server/client.py", line 533, in annotate
    r = self._request(text.encode('utf-8'), request_properties, reset_default, **kwargs)
  File "/home/user18/anaconda3/lib/python3.9/site-packages/stanza/server/client.py", line 447, in _request
    self.ensure_alive()
  File "/home/user18/anaconda3/lib/python3.9/site-packages/stanza/server/client.py", line 221, in ensure_alive
    raise PermanentlyFailedException("Timed out waiting for service to come alive.")
stanza.server.client.PermanentlyFailedException: Timed out waiting for service to come alive.
[2022-11-15 08:54:07,760 INFO] 1 ASER Extractors are closed.

**Comment by seanliu96** [comment]
Could you please provide more details about your error?

**Comment by fpalll** [comment]
> Could you please provide more details about your error?

I have follow the setting up step according to the ASER website. However when I run the following code. These error appeared.

!aser-pipe -n_extractors 1 -n_workers 1 \
-corenlp_path "stanford-corenlp-3.9.2" -base_corenlp_port 9000 \
-raw_dir "raw" -processed_dir "processed" \
-core_kg_dir "core" -full_kg_dir "full" \
-eventuality_frequency_threshold 0 -relation_weight_threshold 0 \
-concept_kg_dir "concept" -concept_method probase -probase_path "probase.txt" \
-eventuality_threshold_to_conceptualize 0 -concept_weight_threshold 0 -concept_topk 5 \
-log_path "core/aser_pipe.log"

**Comment by seanliu96** [comment]
One possible reason is the corenlp server. Did you check whether you can start corenlp server offline?
[Here](https://stanfordnlp.github.io/CoreNLP/corenlp-server.html) provides some usages. Please try to start the server and post data to check.

**Comment by fpalll** [comment]
> One possible reason is the corenlp server. Did you check whether you can start corenlp server offline? [Here](https://stanfordnlp.github.io/CoreNLP/corenlp-server.html) provides some usages. Please try to start the server and post data to check.

2022-11-16 08:45:34 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
2022-11-16 08:45:34 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
2022-11-16 08:45:34 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
/home/user18/anaconda3/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.22.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
[probase-conceptualize] Loading Probase files...
[probase-conceptualize] Building index...
100%|███████████████████████████| 33377320/33377320 [02:13<00:00, 250956.29it/s]
[probase-conceptualize] Loading data finished in 142.09 s
[2022-11-16 08:47:57,209 INFO] Starting the pipeline.
[2022-11-16 08:47:57,209 INFO] Processing raw data from raw.
[2022-11-16 08:47:57,209 INFO] Number of files: 1.
2022-11-16 08:47:57 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
[2022-11-16 08:47:57,209 WARNING] Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
2022-11-16 08:48:09 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
[2022-11-16 08:48:09,182 WARNING] Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
2022-11-16 08:48:09 WARNING: Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
[2022-11-16 08:48:09,739 WARNING] Setting 'start_server' to a boolean value when constructing CoreNLPClient is deprecated and will stop to function in a future version of stanza. Please consider switching to using a value from stanza.server.StartServer.
[2022-11-16 08:48:10,779 INFO] 27 eventualities (27 unique) have been extracted.
[2022-11-16 08:48:10,779 INFO] 19 relations (18 unique) have been extracted.
[2022-11-16 08:48:10,779 INFO] Storing inverted tables.
[2022-11-16 08:48:10,779 INFO] Building the full KG.
[2022-11-16 08:48:11,145 INFO] Done.
[2022-11-16 08:48:11,145 INFO] Filtering low-frequency eventualities.
[2022-11-16 08:48:11,145 INFO] 27 eventualities (27 unique) will be inserted into the core KG.
[2022-11-16 08:48:11,145 INFO] Filtering low-frequency relations.
[2022-11-16 08:48:11,145 INFO] 19 relations (18 unique) will be inserted into the core KG.
[2022-11-16 08:48:11,145 INFO] Copying the full KG as the core KG.
[2022-11-16 08:48:11,146 INFO] Conceptualizing eventualities.
[2022-11-16 08:48:11,146 INFO] 27 eventualities (27 unique) will be conceptualized by probase.
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 500.22it/s]
[2022-11-16 08:48:11,200 INFO] 132 unique concepts  will be inserted into the concept KG.
[2022-11-16 08:48:11,200 INFO] 139 unique concept-instance pairs  will be inserted into the concept KG.
[2022-11-16 08:48:11,200 INFO] Building the concept KG.
[2022-11-16 08:48:11,480 INFO] Inserting concepts.
[2022-11-16 08:48:11,588 INFO] Inserting concept-instance pairs.
100%|███████████████████████████████████████| 18/18 [00:00<00:00, 138273.76it/s]
100%|██████████████████████████████████████| 132/132 [00:00<00:00, 19101.85it/s]
[2022-11-16 08:48:11,707 INFO] 322 unique concept-concept relations will be inserted into the concept KG.
[2022-11-16 08:48:11,798 INFO] Done.
[2022-11-16 08:48:11,798 INFO] Ending.
[2022-11-16 08:48:11,799 INFO] 1 ASER Extractors are closed.


--> does it means that the setting up for ASER pipeline is done??

**Comment by seanliu96** [comment]
Yes, the process finished successfully.

**Comment by fpalll** [comment]
> Yes, the process finished successfully.

Thank you so much^^

**Comment by seanliu96** [comment]
Maybe you need to check the version of your corenlp because our rules are designed for corenlp 3.9.2.

**Comment by seanliu96** [comment]
Yes, these files are exact results.
